disabled_rules:
opt_in_rules:
  - empty_count
  - redundant_nil_coalescing
  - prohibited_super_call
  - overridden_super_call
  - operator_usage_whitespace
  - number_separator
  - nimble_operator
  - force_unwrapping
  - explicit_init
  - conditional_returns_on_newline
  - closure_spacing
  - closure_end_indentation
  - attributes
  - file_header 
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - multiline_arguments
  - multiline_parameters
  - prefixed_toplevel_constant
  - private_outlet
  - private_action
  - single_test_class
  - sorted_imports
  - switch_case_alignment
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - fatal_error_message
  - yoda_condition
  - discouraged_object_literal
  - literal_expression_end_indentation 
  - contains_over_first_not_nil
  - first_where
  - explicit_acl
  - explicit_top_level_acl
  - explicit_enum_raw_value
  - untyped_error_in_catch
  - trailing_whitespace
  - sorted_first_last
  - override_in_extension
  - no_grouping_extension
  - lower_acl_than_parent
  - joined_default_parameter
  - empty_string
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
included:
  - Source
  - Tests
excluded:
  - fastlane
  - Carthage

force_cast:
  severity: warning
force_try:
  severity: warning
trailing_whitespace:
  ignores_empty_lines: true
function_parameter_count:
  warning: 9
  error: 12
function_body_length:
  warning: 60
  error: 100
cyclomatic_complexity:
  warning: 40
  error: 60
type_body_length:
  warning: 400
  error: 500
line_length:
  warning: 250
  error: 400
file_length:
  warning: 700
  error: 1200
type_name:
  min_length: 2
  max_length: 50
  excluded:
    - iPhone
    - my
identifier_name:
  min_length: 3
  max_length: 50
  excluded:
    - i
    - to
    - x
    - y
    - z
    - a
    - b
    - ac
    - vc
    - map
    - app
    - id    
reporter: "xcode"
