language: swift
script:
- carthage bootstrap --configuration Debug --no-use-binaries --cache-builds
- xcodebuild -project Power.xcodeproj -scheme Power-tvOS -destination "platform=tvOS Simulator,name=Apple TV" -configuration Debug -enableCodeCoverage YES build test | xcpretty
- xcodebuild -project Power.xcodeproj -scheme Power-iOS -destination "platform=iOS Simulator,name=iPhone 7" -configuration Debug -enableCodeCoverage YES build test | xcpretty
- xcodebuild -project Power.xcodeproj -scheme Power-macOS -configuration Debug -enableCodeCoverage YES build test | xcpretty
after_success:
- bash <(curl -s https://codecov.io/bash)
