language: objective-c
script:
   - carthage bootstrap --configuration Debug --no-use-binaries --cache-builds
   - fastlane scan --scheme Power-iOS
   - fastlane scan --scheme Power-macOS
   - fastlane scan --scheme Power-tvOS
